(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const go=p=>window.CoworkV5?.go?.(p);
function ensureEvents(){if($('[data-page="events"]'))return;const anchor=$('[data-page="publish"]');if(!anchor)return;anchor.insertAdjacentHTML('beforebegin',`<section class="screen" data-page="events"><div class="head"><h1 class="title">Événements</h1><button class="circleBtn" type="button" data-go="map" aria-label="Voir sur la carte"><span class="mapIco">⌖</span></button></div><div class="search slim">⌕<input id="eventSearch" type="search" placeholder="Atelier, rencontre, session…"></div><div class="eventFilters quickFilterRow"><button class="quickFilter on" data-event-filter="all">Tous</button><button class="quickFilter" data-event-filter="today">Aujourd’hui</button><button class="quickFilter" data-event-filter="near">Près de moi</button><button class="quickFilter" data-event-filter="free">Gratuit</button></div><div id="eventList"><article class="eventCard" data-event-tags="today free"><div class="eventDate"><b>12</b><small>SEP</small></div><div><h3>Session coworking ouverte</h3><p>Rennes · Aujourd’hui · Gratuit</p><button type="button" data-go="people">Voir les participants</button></div></article><article class="eventCard" data-event-tags="near"><div class="eventDate"><b>14</b><small>SEP</small></div><div><h3>Atelier fabrication & prototypage</h3><p>Bruz · Atelier partagé</p><button type="button" data-go="map">Voir sur la carte</button></div></article></div></section>`)}
function repairTabs(){const tabs=$('[data-page="explore"] .tabs');if(!tabs)return;const b=[...tabs.children];if(b[0]){b[0].type='button';b[0].removeAttribute('data-go')}if(b[1])b[1].dataset.go='people';if(b[2])b[2].dataset.go='events';if(b[3])b[3].dataset.go='spaces';}
function repairButtons(){$$('button').forEach(b=>{if(!b.type)b.type='button'});$$('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');}
function routeAudit(){document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(!b)return;const target=b.dataset.go;if(target==='spaces'&&!$('[data-page="spaces"]'))return;const screen=$(`[data-page="${CSS.escape(target)}"]`);if(!screen&&target!=='spaces'){e.preventDefault();console.warn('Cowork it: destination absente',target);go('home')}});}
function mapListBridge(){const apply=()=>{const mapScreen=$('#mapScreen');if(!mapScreen)return;let btn=$('#mapListToggle');if(!btn){btn=document.createElement('button');btn.id='mapListToggle';btn.className='mapListToggle';btn.type='button';btn.textContent='☰ Liste';btn.onclick=()=>go('explore');mapScreen.appendChild(btn)}const q=$('#exploreSearch')?.value?.trim();const mq=$('#mapQuery');if(q&&mq&&!mq.dataset.synced){mq.value=q;mq.dataset.synced='1';mq.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))}};new MutationObserver(()=>{if($('#mapScreen.active'))setTimeout(apply,80)}).observe($('.phone'),{subtree:true,attributes:true,childList:true,attributeFilter:['class']});document.addEventListener('click',e=>{if(e.target.closest('[data-go="map"]'))setTimeout(apply,140)})}
function quickFilters(){document.addEventListener('click',e=>{const q=e.target.closest('.quickFilter');if(!q||q.hasAttribute('data-event-filter'))return;const screen=q.closest('.screen');if(!screen)return;const txt=q.textContent.trim().toLowerCase();const row=q.parentElement;if(txt==='tous'){row.querySelectorAll('.quickFilter').forEach(x=>x.classList.toggle('on',x===q));if(screen.dataset.page==='spaces')$('[data-space-tool="all"]')?.click();return}q.classList.toggle('on');row.querySelector('.quickFilter[data-qf="tous"]')?.classList.remove('on');if(screen.dataset.page==='people'){if(txt.includes('en ligne'))screen.querySelector('.seg button:nth-child(2)')?.click();else if(txt.includes('près'))screen.querySelector('.seg button:nth-child(3)')?.click();return}if(screen.dataset.page==='spaces'){const map={wifi:'wifi',gratuit:'free',outils:'tools',"aujourd’hui":'instant'};const k=Object.keys(map).find(k=>txt.includes(k));if(k)$(`[data-space-tool="${map[k]}"]`)?.click();return}if(screen.dataset.page==='explore'){const pill=$$('.pillBtn',screen).find(p=>p.textContent.trim().toLowerCase().replace('‑','-').includes(txt.replace('wifi','wi-fi')));pill?.click()}} ,true)}
function eventFilters(){document.addEventListener('click',e=>{const b=e.target.closest('[data-event-filter]');if(!b)return;const row=b.parentElement;row.querySelectorAll('[data-event-filter]').forEach(x=>x.classList.toggle('on',x===b));const f=b.dataset.eventFilter;$$('#eventList .eventCard').forEach(c=>c.hidden=f!=='all'&&!c.dataset.eventTags.split(' ').includes(f))});$('#eventSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('#eventList .eventCard').forEach(c=>c.hidden=q&&!c.innerText.toLowerCase().includes(q))})}
function workingSort(){const sel=$('.sortSelect');if(!sel)return;sel.addEventListener('change',()=>{const host=$('#places');if(!host)return;const cards=$$('.place',host);const n=s=>parseFloat((s.match(/([0-9]+(?:[,.][0-9]+)?)/)||[])[1]?.replace(',','.')||9999);cards.sort((a,b)=>{if(sel.value==='Note')return n(b.querySelector('.star')?.textContent||'0')-n(a.querySelector('.star')?.textContent||'0');if(sel.value==='Disponibilité')return (b.innerText.toLowerCase().includes('ouvert')?1:0)-(a.innerText.toLowerCase().includes('ouvert')?1:0);return n(a.innerText)-n(b.innerText)}).forEach(c=>host.appendChild(c))})}
function activeTabSync(){const sync=()=>{const p=$('.screen.active')?.dataset.page;const tabs=$('[data-page="explore"] .tabs');if(tabs){[...tabs.children].forEach((b,i)=>b.classList.toggle('on',(p==='explore'&&i===0)||(p==='people'&&i===1)||(p==='events'&&i===2)||(p==='spaces'&&i===3)))}};new MutationObserver(sync).observe($('.phone'),{subtree:true,attributes:true,attributeFilter:['class']});sync()}
function boot(){ensureEvents();repairTabs();repairButtons();routeAudit();mapListBridge();quickFilters();eventFilters();workingSort();activeTabSync();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();