(()=>{
'use strict';
const SUPABASE_URL='https://xiodvkpdghqgybkktpuq.supabase.co';
const PUBLIC_KEY='sb_publishable_ckxMTL_0pDavdyNN8EH9Hg_7z1v7_x-';
const REVIEWS='place_reviews',VALIDATIONS='place_validations';
let stats=new Map(),lastKey='',syncTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const token=()=>{try{return sessionStorage.getItem('coworkit3_access_token')||''}catch{return''}};
const user=()=>{try{return JSON.parse(sessionStorage.getItem('coworkit3_user')||'null')}catch{return null}};
const headers=(write=false)=>({'apikey':PUBLIC_KEY,'Authorization':'Bearer '+(token()||PUBLIC_KEY),'Content-Type':'application/json',...(write?{'Prefer':'resolution=merge-duplicates,return=minimal'}:{})});
function injectStyle(){if(document.getElementById('communityMapStyle'))return;const s=document.createElement('style');s.id='communityMapStyle';s.textContent=`
 #mapList{position:relative}.gm-results-head{position:sticky;top:0;z-index:10;background:rgba(255,255,255,.97);backdrop-filter:blur(12px);padding:12px 10px 10px;border-bottom:1px solid rgba(38,21,77,.08)}.gm-results-top{display:flex;align-items:center;justify-content:space-between;gap:10px}.gm-results-title{font-size:16px;font-weight:850}.gm-count{font-size:12px;color:#746b80}.gm-sort{display:flex;gap:6px;overflow:auto;padding-top:8px;scrollbar-width:none}.gm-sort::-webkit-scrollbar{display:none}.gm-sort button{border:1px solid rgba(38,21,77,.12);background:#fff;padding:7px 10px;border-radius:999px;font-size:11px;font-weight:700;white-space:nowrap}.gm-sort button.active{background:#26154d;color:#fff;border-color:#26154d}.gm-mobile-tabs{display:none}.world-card{padding:13px 10px!important;border-radius:14px;margin:4px 4px 8px!important;border:1px solid rgba(38,21,77,.08)!important;background:#fff;box-shadow:0 2px 8px rgba(38,21,77,.04);transition:.16s ease}.world-card:hover,.world-card.gm-selected{background:#faf7ff!important;border-color:rgba(109,40,217,.32)!important;box-shadow:0 8px 22px rgba(38,21,77,.09)}.gm-community{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.gm-badge{font-size:10px;font-weight:750;padding:4px 7px;border-radius:999px;background:#f2eef7}.gm-badge.good{background:#eaf8ef;color:#166534}.gm-badge.warn{background:#fff2e5;color:#9a3412}.gm-card-actions{display:flex;gap:6px;margin-top:9px}.gm-card-actions button{padding:7px 9px;border:0;border-radius:10px;font-size:11px;font-weight:750;cursor:pointer}.gm-review-btn{background:#26154d;color:#fff}.gm-valid-btn{background:#eee8f7;color:#3b2862}.gm-modal-backdrop{position:fixed;inset:0;background:rgba(23,15,37,.46);z-index:2000;display:grid;place-items:center;padding:18px}.gm-modal{width:min(520px,100%);max-height:82vh;overflow:auto;background:#fff;border-radius:22px;padding:18px;box-shadow:0 30px 80px rgba(0,0,0,.25)}.gm-modal h3{margin:0 0 10px}.gm-stars{display:flex;gap:5px;margin:10px 0}.gm-stars button{font-size:27px;background:none;border:0;cursor:pointer;filter:grayscale(1);opacity:.45}.gm-stars button.on{filter:none;opacity:1}.gm-modal textarea{width:100%;min-height:100px;resize:vertical;border:1px solid #ddd1e8;border-radius:12px;padding:10px;font:inherit}.gm-modal .actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.gm-modal .actions button{padding:9px 12px;border-radius:11px;border:0;font-weight:750}.gm-modal .primary{background:#26154d;color:#fff}.gm-modal .secondary{background:#eee8f7;color:#26154d}
 @media(max-width:800px){.map-shell{display:block!important}.map-wrap{height:54vh!important}.map-side{position:fixed!important;left:0;right:0;bottom:70px;z-index:900;max-height:43vh;overflow:auto;background:#fff;border-radius:20px 20px 0 0;box-shadow:0 -10px 35px rgba(0,0,0,.18);padding-top:0!important;transform:translateY(calc(100% - 74px));transition:transform .22s ease}.map-side.gm-open{transform:translateY(0)}.gm-results-head{padding-top:8px}.gm-results-head:before{content:'';display:block;width:38px;height:4px;border-radius:4px;background:#d5cddd;margin:0 auto 9px}.gm-mobile-tabs{display:flex;position:absolute;right:12px;top:12px;z-index:700;background:#fff;border-radius:999px;box-shadow:0 3px 14px rgba(0,0,0,.15);overflow:hidden}.gm-mobile-tabs button{border:0;background:#fff;padding:8px 11px;font-weight:750}.gm-mobile-tabs button.active{background:#26154d;color:#fff}}
 `;document.head.appendChild(s)}
function resultIds(){return (window.CoworkWorldMap?.getResults?.()||[]).map(x=>x.id).filter(Boolean)}
async function fetchTable(table,ids){if(!ids.length)return[];const chunks=[];for(let i=0;i<ids.length;i+=60)chunks.push(ids.slice(i,i+60));const all=[];for(const c of chunks){const encoded=c.map(x=>'"'+String(x).replace(/"/g,'')+'"').join(',');const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?select=*&place_key=in.(${encodeURIComponent(encoded)})`,{headers:headers()});if(r.ok)all.push(...await r.json())}return all}
async function refreshStats(){const ids=resultIds();const key=ids.slice().sort().join('|');if(!ids.length||key===lastKey)return;lastKey=key;try{const [reviews,vals]=await Promise.all([fetchTable(REVIEWS,ids),fetchTable(VALIDATIONS,ids)]);const m=new Map();ids.forEach(id=>m.set(id,{rating:0,reviews:0,correct:0,outdated:0}));reviews.forEach(r=>{const s=m.get(r.place_key);if(!s)return;s.rating+=Number(r.rating)||0;s.reviews++});vals.forEach(v=>{const s=m.get(v.place_key);if(!s)return;if(v.status==='correct')s.correct++;else if(v.status==='outdated')s.outdated++});m.forEach(s=>{s.rating=s.reviews?s.rating/s.reviews:0});stats=m;enhanceList()}catch(e){console.warn('community stats',e);lastKey=''}}
function headerHtml(count){return `<div class="gm-results-head" data-community-ui><div class="gm-results-top"><div><div class="gm-results-title">Résultats dans cette zone</div><div class="gm-count">${count} proposition${count>1?'s':''} · carte synchronisée</div></div></div><div class="gm-sort"><button class="active" data-gm-sort="distance">Plus proches</button><button data-gm-sort="rating">Mieux notés</button><button data-gm-sort="verified">Plus fiables</button></div></div>`}
function enhanceList(){const side=document.getElementById('mapList');if(!side)return;const cards=[...side.querySelectorAll('.world-card')];let h=side.querySelector('.gm-results-head');if(!h){side.insertAdjacentHTML('afterbegin',headerHtml(cards.length));h=side.querySelector('.gm-results-head')}else{const c=h.querySelector('.gm-count'),txt=`${cards.length} proposition${cards.length>1?'s':''} · carte synchronisée`;if(c&&c.textContent!==txt)c.textContent=txt}
 cards.forEach(card=>{const id=card.dataset.worldId;if(!id)return;const s=stats.get(id)||{rating:0,reviews:0,correct:0,outdated:0};let box=card.querySelector('.gm-community');if(!box){box=document.createElement('div');box.className='gm-community';const source=card.querySelector('.world-source');source?.insertAdjacentElement('beforebegin',box);const actions=document.createElement('div');actions.className='gm-card-actions';actions.innerHTML=`<button class="gm-review-btn" data-gm-review="${esc(id)}">★ Donner un avis</button><button class="gm-valid-btn" data-gm-valid="${esc(id)}">✓ Vérifier</button>`;source?.insertAdjacentElement('beforebegin',actions)}
 const conf=s.correct+s.outdated,reliability=conf?Math.round(100*s.correct/conf):null,next=`${s.reviews?`<span class="gm-badge">★ ${s.rating.toFixed(1)} · ${s.reviews} avis</span>`:`<span class="gm-badge">Aucun avis Cowork it</span>`}${reliability!==null?`<span class="gm-badge ${reliability>=70?'good':'warn'}">${reliability}% infos confirmées</span>`:''}`;if(box.innerHTML!==next)box.innerHTML=next;
 });
}
function sortCards(mode){const side=document.getElementById('mapList');if(!side)return;const cards=[...side.querySelectorAll('.world-card')];cards.sort((a,b)=>{const sa=stats.get(a.dataset.worldId)||{},sb=stats.get(b.dataset.worldId)||{};if(mode==='rating')return (sb.rating||0)-(sa.rating||0);if(mode==='verified'){const ra=(sa.correct||0)-2*(sa.outdated||0),rb=(sb.correct||0)-2*(sb.outdated||0);return rb-ra}const da=parseFloat((a.querySelector('.world-card-meta')?.textContent.match(/([\d,.]+)\s*km/)||[])[1]?.replace(',','.')||'9999'),db=parseFloat((b.querySelector('.world-card-meta')?.textContent.match(/([\d,.]+)\s*km/)||[])[1]?.replace(',','.')||'9999');return da-db});cards.forEach(c=>side.appendChild(c));side.querySelectorAll('[data-gm-sort]').forEach(b=>b.classList.toggle('active',b.dataset.gmSort===mode))}
function requireLogin(){if(user()?.id&&token())return true;alert('Connectez-vous à Cowork it pour publier un avis ou valider les informations.');return false}
function modal(html){document.querySelector('.gm-modal-backdrop')?.remove();const d=document.createElement('div');d.className='gm-modal-backdrop';d.innerHTML=`<div class="gm-modal">${html}</div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-gm-close]'))d.remove()})}
function openReview(placeKey){if(!requireLogin())return;let rating=5;modal(`<h3>Votre avis Cowork it</h3><p>Partagez uniquement votre expérience réelle de ce lieu.</p><div class="gm-stars">${[1,2,3,4,5].map(n=>`<button class="on" data-star="${n}">★</button>`).join('')}</div><textarea id="gmReviewText" maxlength="1200" placeholder="Wi‑Fi, calme, prises, accueil, facilité pour travailler…"></textarea><div class="actions"><button class="secondary" data-gm-close>Annuler</button><button class="primary" id="gmSaveReview">Publier</button></div>`);document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{rating=+b.dataset.star;document.querySelectorAll('[data-star]').forEach(x=>x.classList.toggle('on',+x.dataset.star<=rating))});document.getElementById('gmSaveReview').onclick=async()=>{try{const text=document.getElementById('gmReviewText').value.trim();await upsert(REVIEWS,{place_key:placeKey,user_id:user().id,rating,comment:text},'place_key,user_id');document.querySelector('.gm-modal-backdrop')?.remove();lastKey='';refreshStats()}catch(e){alert('Avis non publié : '+e.message)}}}
async function validate(placeKey,status){if(!requireLogin())return;await upsert(VALIDATIONS,{place_key:placeKey,user_id:user().id,status},'place_key,user_id');lastKey='';refreshStats()}
function openValidation(placeKey){if(!requireLogin())return;modal(`<h3>Les informations sont-elles à jour ?</h3><p>Votre validation aide les autres utilisateurs à éviter les horaires, services ou accès obsolètes.</p><div class="actions"><button class="secondary" data-gm-outdated>⚠ À actualiser</button><button class="primary" data-gm-correct>✓ Informations correctes</button></div>`);document.querySelector('[data-gm-correct]').onclick=async()=>{try{await validate(placeKey,'correct');document.querySelector('.gm-modal-backdrop')?.remove()}catch(e){alert('Validation non enregistrée : '+e.message)}};document.querySelector('[data-gm-outdated]').onclick=async()=>{try{await validate(placeKey,'outdated');document.querySelector('.gm-modal-backdrop')?.remove()}catch(e){alert('Validation non enregistrée : '+e.message)}}}
async function upsert(table,row,conflict){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:headers(true),body:JSON.stringify(row)});if(!r.ok){const t=await r.text();throw new Error(t||String(r.status))}}
function mobileControls(){const wrap=document.querySelector('.map-wrap');if(!wrap||wrap.querySelector('.gm-mobile-tabs'))return;const d=document.createElement('div');d.className='gm-mobile-tabs';d.innerHTML='<button class="active" data-gm-view="map">Carte</button><button data-gm-view="list">Liste</button>';wrap.appendChild(d)}
function setMobileView(v){const side=document.getElementById('mapList');side?.classList.toggle('gm-open',v==='list');document.querySelectorAll('[data-gm-view]').forEach(b=>b.classList.toggle('active',b.dataset.gmView===v))}
function boot(){injectStyle();mobileControls();const side=document.getElementById('mapList');if(!side)return;const obs=new MutationObserver(()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>{enhanceList();refreshStats()},180)});obs.observe(side,{childList:true,subtree:true});setInterval(()=>{enhanceList();refreshStats()},3000);enhanceList();refreshStats();document.addEventListener('click',e=>{const r=e.target.closest('[data-gm-review]');if(r){e.stopPropagation();openReview(r.dataset.gmReview);return}const v=e.target.closest('[data-gm-valid]');if(v){e.stopPropagation();openValidation(v.dataset.gmValid);return}const s=e.target.closest('[data-gm-sort]');if(s){sortCards(s.dataset.gmSort);return}const view=e.target.closest('[data-gm-view]');if(view){setMobileView(view.dataset.gmView);return}const card=e.target.closest('.world-card');if(card){document.querySelectorAll('.world-card').forEach(x=>x.classList.remove('gm-selected'));card.classList.add('gm-selected')}})}
window.addEventListener('load',()=>setTimeout(boot,350));
})();
