(()=>{
'use strict';
const SUPABASE_URL='https://xiodvkpdghqgybkktpuq.supabase.co';
const PUBLIC_KEY='sb_publishable_ckxMTL_0pDavdyNN8EH9Hg_7z1v7_x-';
const REVIEWS='place_reviews',VALIDATIONS='place_validations';
let stats=new Map(),lastKey='',sortMode='distance',viewMode='map',busy=false,refreshTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const token=()=>{try{return sessionStorage.getItem('coworkit3_access_token')||''}catch{return''}};
const user=()=>{try{return JSON.parse(sessionStorage.getItem('coworkit3_user')||'null')}catch{return null}};
const headers=(write=false)=>({'apikey':PUBLIC_KEY,'Authorization':'Bearer '+(token()||PUBLIC_KEY),'Content-Type':'application/json',...(write?{'Prefer':'resolution=merge-duplicates,return=minimal'}:{})});
function injectStyle(){if(document.getElementById('coworkMapExperienceStyle'))return;const s=document.createElement('style');s.id='coworkMapExperienceStyle';s.textContent=`
 #page-map{--mapPurple:#2d185b;--mapYellow:#ffd62e;--mapCream:#fffaf0;--mapLine:rgba(45,24,91,.11)}
 .cowork-map-modebar{display:none;align-items:center;justify-content:space-between;gap:10px;margin:0 0 10px;padding:5px;background:#eee8f5;border:1px solid var(--mapLine);border-radius:16px}
 .cowork-map-modebar .mode-group{display:grid;grid-template-columns:1fr 1fr;gap:4px;width:100%}
 .cowork-map-modebar button{border:0;border-radius:12px;padding:10px 14px;background:transparent;color:var(--mapPurple);font-weight:850}
 .cowork-map-modebar button.active{background:var(--mapPurple);color:#fff;box-shadow:0 4px 12px rgba(45,24,91,.18)}
 .cowork-map-summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px 14px;background:#fff;border:1px solid var(--mapLine);border-radius:18px;position:sticky;top:0;z-index:20}
 .cowork-map-summary strong{display:block;font-size:16px}.cowork-map-summary small{color:#776c87}
 .cowork-map-sort{display:flex;gap:6px;overflow:auto;padding:9px 2px 10px;scrollbar-width:none}.cowork-map-sort::-webkit-scrollbar{display:none}
 .cowork-map-sort button{white-space:nowrap;border:1px solid var(--mapLine);background:#fff;color:var(--mapPurple);padding:8px 11px;border-radius:999px;font-size:11px;font-weight:800}
 .cowork-map-sort button.active{background:var(--mapYellow);border-color:var(--mapYellow)}
 #mapList{padding:0 2px 12px;scrollbar-width:thin}
 #mapList .world-list-title{display:none!important}
 #mapList .world-card{display:block!important;margin:0 0 9px!important;padding:13px!important;border:1px solid var(--mapLine)!important;border-radius:18px!important;background:#fff!important;box-shadow:none!important;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}
 #mapList .world-card:hover,#mapList .world-card.cowork-selected{transform:translateY(-1px);border-color:rgba(74,37,122,.32)!important;box-shadow:0 9px 24px rgba(45,24,91,.09)!important}
 .cowork-result-top{display:flex;align-items:flex-start;gap:10px}.cowork-result-index{flex:0 0 28px;height:28px;border-radius:10px;background:var(--mapPurple);color:#fff;display:grid;place-items:center;font-size:11px;font-weight:900}
 .cowork-result-main{min-width:0;flex:1}.cowork-result-title{font-weight:900;font-size:15px;line-height:1.2}.cowork-result-meta{font-size:12px;color:#776c87;margin-top:4px}
 .cowork-result-signals{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.cowork-signal{font-size:10px;font-weight:800;padding:5px 7px;border-radius:999px;background:#f2edf6;color:#594868}.cowork-signal.good{background:#e9f8ef;color:#166534}.cowork-signal.warn{background:#fff0df;color:#9a3412}
 .cowork-result-actions{display:flex;gap:6px;margin-top:10px}.cowork-result-actions button{border:0;border-radius:11px;padding:8px 10px;font-size:11px;font-weight:850}.cowork-review{background:var(--mapPurple);color:#fff}.cowork-verify{background:#eee8f5;color:var(--mapPurple)}
 .cowork-community-modal{position:fixed;inset:0;z-index:2200;background:rgba(24,15,38,.48);display:grid;place-items:center;padding:18px}.cowork-community-dialog{width:min(500px,100%);max-height:86vh;overflow:auto;background:var(--mapCream);border-radius:24px;padding:19px;box-shadow:0 28px 85px rgba(0,0,0,.28)}.cowork-community-dialog h3{margin:0 0 8px}.cowork-community-dialog textarea{width:100%;min-height:110px;border:1px solid var(--mapLine);border-radius:14px;padding:11px;background:#fff}.cowork-stars{display:flex;gap:5px;margin:10px 0}.cowork-stars button{border:0;background:transparent;font-size:27px;opacity:.32}.cowork-stars button.on{opacity:1}.cowork-dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.cowork-dialog-actions button{border:0;border-radius:12px;padding:10px 13px;font-weight:850}.cowork-dialog-actions .primary{background:var(--mapPurple);color:#fff}.cowork-dialog-actions .secondary{background:#eee8f5;color:var(--mapPurple)}
 @media(min-width:1101px){#page-map .map-shell{grid-template-columns:minmax(0,1.55fr) minmax(340px,.72fr)!important;gap:16px!important}#page-map .map-side{display:block!important;overflow:auto!important}}
 @media(min-width:861px) and (max-width:1100px){#page-map .map-shell{display:grid!important;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr)!important;gap:12px!important}#page-map .map-side{display:block!important;overflow:auto!important}#page-map .map-wrap,#page-map #map{min-height:620px!important}}
 @media(max-width:860px){
   #page-map .cowork-map-modebar{display:flex}
   #page-map .map-shell{display:block!important;height:auto!important;min-height:0!important}
   #page-map .map-wrap{height:calc(100dvh - 285px)!important;min-height:430px!important;border-radius:22px!important}
   #page-map #map{height:100%!important;min-height:430px!important}
   #page-map .map-side{display:none!important;position:static!important;max-height:none!important;overflow:visible!important;background:transparent!important;border-radius:0!important;box-shadow:none!important;transform:none!important;padding:0!important}
   #page-map.cowork-list-mode .map-wrap{display:none!important}
   #page-map.cowork-list-mode .map-side{display:block!important}
   #page-map.cowork-list-mode .map-shell{min-height:calc(100dvh - 255px)!important}
   #page-map .map-tools{top:10px;left:10px;right:10px;overflow:auto;padding-bottom:3px;scrollbar-width:none}
   #page-map .cowork-map-legend{display:none!important}
   #page-map .section-head{margin-bottom:10px}
   #page-map .section-head .secondary{padding:10px 12px}
 }
 @media(max-width:500px){#page-map .map-wrap{height:calc(100dvh - 300px)!important;min-height:390px!important}.cowork-map-summary{border-radius:15px}.cowork-result-actions button{flex:1}}
 `;document.head.appendChild(s)}
function buildModeBar(){const page=document.getElementById('page-map'),shell=page?.querySelector('.map-shell');if(!page||!shell||page.querySelector('.cowork-map-modebar'))return;const bar=document.createElement('div');bar.className='cowork-map-modebar';bar.innerHTML='<div class="mode-group"><button type="button" class="active" data-cowork-map-view="map">⌖ Carte</button><button type="button" data-cowork-map-view="list">☰ Liste</button></div>';shell.insertAdjacentElement('beforebegin',bar)}
function resultIds(){return (window.CoworkWorldMap?.getResults?.()||[]).map(x=>x.id).filter(Boolean)}
async function fetchTable(table,ids){if(!ids.length)return[];const all=[];for(let i=0;i<ids.length;i+=50){const q=ids.slice(i,i+50).map(x=>'"'+String(x).replace(/"/g,'')+'"').join(',');const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?select=*&place_key=in.(${encodeURIComponent(q)})`,{headers:headers()});if(r.ok)all.push(...await r.json())}return all}
async function refreshStats(force=false){const ids=resultIds(),key=ids.slice().sort().join('|');if(!ids.length){stats=new Map();decorate();return}if(!force&&key===lastKey)return;lastKey=key;try{const [reviews,vals]=await Promise.all([fetchTable(REVIEWS,ids),fetchTable(VALIDATIONS,ids)]);const m=new Map(ids.map(id=>[id,{rating:0,reviews:0,correct:0,outdated:0}]));reviews.forEach(r=>{const s=m.get(r.place_key);if(s){s.rating+=Number(r.rating)||0;s.reviews++}});vals.forEach(v=>{const s=m.get(v.place_key);if(s){if(v.status==='correct')s.correct++;if(v.status==='outdated')s.outdated++}});m.forEach(s=>{s.rating=s.reviews?s.rating/s.reviews:0});stats=m;decorate()}catch(e){console.warn('Cowork community',e);lastKey=''}}
function parseDistance(card){const txt=card.querySelector('.world-card-meta')?.textContent||card.querySelector('.cowork-result-meta')?.textContent||'';let m=txt.match(/([\d.,]+)\s*km/i);if(m)return parseFloat(m[1].replace(',','.'));m=txt.match(/([\d.,]+)\s*m\b/i);return m?parseFloat(m[1].replace(',','.'))/1000:99999}
function sortedCards(cards){return [...cards].sort((a,b)=>{const sa=stats.get(a.dataset.worldId)||{},sb=stats.get(b.dataset.worldId)||{};if(sortMode==='rating')return (sb.rating||0)-(sa.rating||0)||parseDistance(a)-parseDistance(b);if(sortMode==='verified'){const ca=(sa.correct||0)+(sa.outdated||0),cb=(sb.correct||0)+(sb.outdated||0),ra=ca?sa.correct/ca:0,rb=cb?sb.correct/cb:0;return rb-ra||parseDistance(a)-parseDistance(b)}return parseDistance(a)-parseDistance(b)})}
function ensureSummary(side,count){let s=side.querySelector('.cowork-map-summary');if(!s){s=document.createElement('div');s.className='cowork-map-summary';s.dataset.coworkOwned='1';side.prepend(s)}s.innerHTML=`<div><strong>${count} lieu${count>1?'x':''} dans cette zone</strong><small>Déplacez la carte pour actualiser les propositions</small></div>`;let sort=side.querySelector('.cowork-map-sort');if(!sort){sort=document.createElement('div');sort.className='cowork-map-sort';sort.dataset.coworkOwned='1';s.insertAdjacentElement('afterend',sort)}sort.innerHTML=`<button type="button" data-cowork-sort="distance" class="${sortMode==='distance'?'active':''}">Plus proches</button><button type="button" data-cowork-sort="rating" class="${sortMode==='rating'?'active':''}">Mieux notés</button><button type="button" data-cowork-sort="verified" class="${sortMode==='verified'?'active':''}">Infos fiables</button>`}
function decorate(){if(busy)return;const side=document.getElementById('mapList');if(!side)return;busy=true;try{const cards=[...side.querySelectorAll('.world-card')];ensureSummary(side,cards.length);sortedCards(cards).forEach((card,i)=>{side.appendChild(card);const id=card.dataset.worldId;if(!id)return;const st=stats.get(id)||{rating:0,reviews:0,correct:0,outdated:0};const conf=st.correct+st.outdated,reliability=conf?Math.round(100*st.correct/conf):null;let top=card.querySelector('.cowork-result-top');if(!top){const title=card.querySelector('.world-card-title'),meta=card.querySelector('.world-card-meta');top=document.createElement('div');top.className='cowork-result-top';top.innerHTML='<div class="cowork-result-index"></div><div class="cowork-result-main"><div class="cowork-result-title"></div><div class="cowork-result-meta"></div></div>';card.prepend(top);top.querySelector('.cowork-result-title').textContent=title?.textContent||'';top.querySelector('.cowork-result-meta').textContent=meta?.textContent||'';title?.remove();meta?.remove()}top.querySelector('.cowork-result-index').textContent=String(i+1);let sig=card.querySelector('.cowork-result-signals');if(!sig){sig=document.createElement('div');sig.className='cowork-result-signals';const src=card.querySelector('.world-source');src?.insertAdjacentElement('beforebegin',sig)}sig.innerHTML=`${st.reviews?`<span class="cowork-signal good">★ ${st.rating.toFixed(1)} · ${st.reviews} avis</span>`:'<span class="cowork-signal">Nouveau sur Cowork it</span>'}${reliability!==null?`<span class="cowork-signal ${reliability>=70?'good':'warn'}">${reliability}% confirmé</span>`:''}`;let actions=card.querySelector('.cowork-result-actions');if(!actions){actions=document.createElement('div');actions.className='cowork-result-actions';actions.innerHTML=`<button type="button" class="cowork-review" data-cowork-review="${esc(id)}">★ Avis</button><button type="button" class="cowork-verify" data-cowork-verify="${esc(id)}">✓ Vérifier</button>`;const src=card.querySelector('.world-source');src?.insertAdjacentElement('beforebegin',actions)}})}finally{busy=false}}
function scheduleDecorate(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{decorate();refreshStats()},120)}
function setView(v){viewMode=v==='list'?'list':'map';const page=document.getElementById('page-map');page?.classList.toggle('cowork-list-mode',viewMode==='list');document.querySelectorAll('[data-cowork-map-view]').forEach(b=>b.classList.toggle('active',b.dataset.coworkMapView===viewMode));if(viewMode==='map')setTimeout(()=>window.dispatchEvent(new Event('resize')),80)}
function requireLogin(){if(user()?.id&&token())return true;alert('Connectez-vous à Cowork it pour publier un avis ou confirmer des informations.');return false}
function openDialog(html){document.querySelector('.cowork-community-modal')?.remove();const d=document.createElement('div');d.className='cowork-community-modal';d.innerHTML=`<div class="cowork-community-dialog">${html}</div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-dialog-close]'))d.remove()})}
async function upsert(table,row,conflict){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:headers(true),body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text())}
function review(id){if(!requireLogin())return;let rating=5;openDialog(`<h3>Votre expérience</h3><p>Notez la qualité réelle pour travailler ici : calme, Wi‑Fi, prises, accueil et confort.</p><div class="cowork-stars">${[1,2,3,4,5].map(n=>`<button type="button" class="on" data-review-star="${n}">★</button>`).join('')}</div><textarea id="coworkReviewText" maxlength="1200" placeholder="Votre retour utile aux autres utilisateurs…"></textarea><div class="cowork-dialog-actions"><button class="secondary" data-dialog-close>Annuler</button><button class="primary" id="coworkSaveReview">Publier</button></div>`);document.querySelectorAll('[data-review-star]').forEach(b=>b.onclick=()=>{rating=+b.dataset.reviewStar;document.querySelectorAll('[data-review-star]').forEach(x=>x.classList.toggle('on',+x.dataset.reviewStar<=rating))});document.getElementById('coworkSaveReview').onclick=async()=>{try{await upsert(REVIEWS,{place_key:id,user_id:user().id,rating,comment:document.getElementById('coworkReviewText').value.trim()},'place_key,user_id');document.querySelector('.cowork-community-modal')?.remove();lastKey='';await refreshStats(true)}catch(e){alert('Avis non enregistré : '+e.message)}}}
function verify(id){if(!requireLogin())return;openDialog(`<h3>Ces informations sont-elles correctes ?</h3><p>Une confirmation rapide améliore la fiabilité de la carte pour toute la communauté.</p><div class="cowork-dialog-actions"><button class="secondary" data-verify-status="outdated">⚠ À actualiser</button><button class="primary" data-verify-status="correct">✓ Correctes</button></div>`);document.querySelectorAll('[data-verify-status]').forEach(b=>b.onclick=async()=>{try{await upsert(VALIDATIONS,{place_key:id,user_id:user().id,status:b.dataset.verifyStatus},'place_key,user_id');document.querySelector('.cowork-community-modal')?.remove();lastKey='';await refreshStats(true)}catch(e){alert('Validation non enregistrée : '+e.message)}})}
function boot(){injectStyle();buildModeBar();const side=document.getElementById('mapList');if(!side)return;const obs=new MutationObserver(muts=>{if(busy)return;const external=muts.some(m=>[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1&&!n.matches?.('[data-cowork-owned]')&&!n.closest?.('[data-cowork-owned]')));if(external)scheduleDecorate()});obs.observe(side,{childList:true,subtree:false});decorate();refreshStats(true);document.addEventListener('click',e=>{const v=e.target.closest('[data-cowork-map-view]');if(v){setView(v.dataset.coworkMapView);return}const s=e.target.closest('[data-cowork-sort]');if(s){sortMode=s.dataset.coworkSort;decorate();return}const r=e.target.closest('[data-cowork-review]');if(r){e.stopPropagation();review(r.dataset.coworkReview);return}const q=e.target.closest('[data-cowork-verify]');if(q){e.stopPropagation();verify(q.dataset.coworkVerify);return}const card=e.target.closest('.world-card');if(card){document.querySelectorAll('.world-card').forEach(x=>x.classList.remove('cowork-selected'));card.classList.add('cowork-selected')}});window.addEventListener('resize',()=>{if(innerWidth>860)setView('map')})}
window.addEventListener('load',()=>setTimeout(boot,300));
})();