(()=>{
'use strict';
const LOGO='./icons/icon.svg';
const BASE_PLACES=[
 {id:'cortado',title:'Cortado Café',city:'Rennes',kind:'cafe',desc:'Café · Wi‑Fi · prises à confirmer',distanceKm:1.2,open:'Horaires à vérifier',rating:'4,3',website:'https://cortadocafe.fr/'},
 {id:'360',title:'Le 360',city:'Rennes',kind:'cowork',desc:'Tiers-lieu · associations · salles',distanceKm:2.6,open:'Ouvert en semaine',rating:'4,8',website:'https://360.bzh/'},
 {id:'makeme',title:'Le Lab Makeme',city:'Rennes',kind:'maker',desc:'Fab Lab · CNC · laser · impression 3D',distanceKm:3.1,open:'Créneaux à vérifier',rating:'4,6',website:'https://lelab.makeme.fr/'},
 {id:'mediatheque-guichen',title:'Médiathèque La Chouette',city:'Guichen',kind:'library',desc:'Espace numérique · travail · accès public',distanceKm:18.5,open:'Horaires municipaux',rating:'4,7',website:'https://www.guichenpontrean.fr/mediatheque-et-espace-numerique/'}
];
const PEOPLE=[
 {id:'p1',name:'Lina',age:28,role:'UX Designer · Freelance',activity:'UX Design · Figma · Projets créatifs',place:'Coworking · lieu calme pour travailler et échanger',skills:['UX/UI','Design produit','Prototypage'],lat:48.111,lng:-1.68,online:true,quote:'Je cherche des personnes pour travailler ensemble ou partager un espace régulièrement.'},
 {id:'p2',name:'Yann',age:34,role:'Menuisier · Maker',activity:'Bois · CNC · prototypage',place:'Atelier partagé · fablab · espace de fabrication',skills:['CNC','Bois','Plans'],lat:48.025,lng:-1.746,online:true,quote:'Partant pour fabriquer, échanger des techniques ou avancer à plusieurs sur un projet.'},
 {id:'p3',name:'Sarah',age:31,role:'Chargée de projet associatif',activity:'Production · Réseau · Événementiel',place:'Tiers-lieu · café associatif · salle de réunion',skills:['Production','Réseau','Budget'],lat:48.107,lng:-1.675,online:false,quote:'Je cherche des profils complémentaires pour monter des projets locaux.'},
 {id:'p4',name:'Noé',age:30,role:'Développeur web · Indépendant',activity:'JavaScript · API · PWA',place:'Bibliothèque · coworking calme · Wi‑Fi',skills:['JS','API','PWA'],lat:48.088,lng:-1.71,online:true,quote:'Je travaille souvent en nomade et j’aime partager une session de travail silencieuse.'},
 {id:'p5',name:'Camille',age:29,role:'Illustratrice · DA',activity:'Illustration · Print · Direction artistique',place:'Café calme · atelier créatif · lieu privé',skills:['Illustration','Print','DA'],lat:47.968,lng:-1.796,online:false,quote:'Je cherche un lieu lumineux et des personnes créatives avec qui échanger.'}
];
const hav=(a,b,c,d)=>{const R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function readPublished(){try{return JSON.parse(localStorage.getItem('coworkit-v6-published')||'[]')}catch{return[]}}
function savePublished(v){localStorage.setItem('coworkit-v6-published',JSON.stringify(v))}
function allPlaces(){return [...readPublished().filter(x=>x.type==='place'),...BASE_PLACES]}
function placeCard(p){const url=p.website&&/^https?:\/\//i.test(p.website)?p.website:'';return `<article class="place" data-place-id="${esc(p.id)}"><div class="thumb ${esc(p.kind||'cowork')}"></div><div><button class="logoFav" type="button" aria-label="Ajouter aux favoris"><img src="${LOGO}" alt=""></button><h3>${esc(p.title)}</h3><div class="desc">${esc(p.desc||'Lieu partagé')}</div><div class="row"><span>${esc(p.distanceKm!=null?p.distanceKm.toFixed(1).replace('.',',')+' km':p.city||'')} · <span class="open">${esc(p.open||'À vérifier')}</span></span><span class="star">★ ${esc(p.rating||'—')}</span></div><div class="placeActions">${url?`<a class="siteBtn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Site officiel ↗</a>`:'<button type="button" disabled>Site non renseigné</button>'}<button type="button" data-place-map="${esc(p.title)} ${esc(p.city||'')}">Carte</button></div></div></article>`}
function renderPlaces(){const box=document.getElementById('places');if(!box)return;const q=(document.getElementById('exploreSearch')?.value||'').trim().toLowerCase();const list=allPlaces().filter(p=>!q||[p.title,p.city,p.desc].join(' ').toLowerCase().includes(q));box.innerHTML=list.length?list.map(placeCard).join(''):'<div class="emptyPeople">Aucun lieu avec cette recherche.</div>';renderNearbyPreview()}
function personCard(p,compact=false,distance=null){return `<article class="person${compact?' compact':''}" data-person="${p.id}"><div class="photo"></div><div class="personBody"><div class="personTitle"><h2>${esc(p.name)}${compact?'':`, ${p.age}`}</h2><span class="${p.online?'online':'muted'}">${p.online?'● En ligne':'Hors ligne'}</span></div><div class="role">${esc(p.role)}</div>${distance!=null?`<div class="nearBadge">⌖ ${distance.toFixed(1).replace('.',',')} km</div>`:''}<p class="quote">« ${esc(p.quote)} »</p><div class="proGrid"><div class="pro"><small>Activité professionnelle</small><b>${esc(p.activity)}</b></div><div class="pro"><small>Catégorie de lieu recherchée</small><b>${esc(p.place)}</b></div></div>${compact?'':`<div class="chips">${p.skills.map(s=>`<span class="chip">${esc(s)}</span>`).join('')}</div><div class="meetActions"><button class="round" type="button">×</button><button class="round connect" type="button" data-connect="${p.id}"><img src="${LOGO}" alt="Se connecter"></button><button class="round" type="button">★</button></div>`}</div></article>`}
function renderPeople(mode='discover',loc=null){const screen=document.querySelector('[data-page="people"]');if(!screen)return;let list=[...PEOPLE].map(p=>({...p,_d:loc?hav(loc.lat,loc.lng,p.lat,p.lng):null}));if(mode==='online')list=list.filter(p=>p.online);if(mode==='near'&&loc)list.sort((a,b)=>a._d-b._d);else if(mode==='near'&&!loc)list=[];let host=screen.querySelector('#peopleDynamic');if(!host){screen.querySelector('.person')?.remove();screen.insertAdjacentHTML('beforeend','<div id="peopleDynamic" class="peopleList"></div>');host=screen.querySelector('#peopleDynamic')}host.innerHTML=list.length?list.map(p=>personCard(p,false,p._d)).join(''):'<div class="emptyPeople">Active la géolocalisation pour découvrir les personnes aux alentours.</div>'}
function locatePeople(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>resolve(null),{enableHighAccuracy:false,timeout:7000,maximumAge:300000})})}
async function setPeopleMode(mode){document.querySelectorAll('[data-page="people"] .seg button').forEach((b,i)=>b.classList.toggle('on',(mode==='discover'&&i===0)||(mode==='online'&&i===1)||(mode==='near'&&i===2)));if(mode==='near'){const loc=await locatePeople();renderPeople('near',loc)}else renderPeople(mode)}
async function renderNearbyPreview(){const screen=document.querySelector('[data-page="explore"]');if(!screen)return;let host=screen.querySelector('#nearPeopleExplore');if(!host){const places=document.getElementById('places');places?.insertAdjacentHTML('afterend','<div id="nearPeopleExplore"></div>');host=screen.querySelector('#nearPeopleExplore')}host.innerHTML='<div class="nearPeopleHead"><h2>Personnes aux alentours</h2><button type="button" data-go="people">Tout voir →</button></div><div class="emptyPeople">Recherche de profils proches…</div>';const loc=await locatePeople();let list=[...PEOPLE].map(p=>({...p,_d:loc?hav(loc.lat,loc.lng,p.lat,p.lng):null}));if(loc)list.sort((a,b)=>a._d-b._d);host.innerHTML=`<div class="nearPeopleHead"><h2>Personnes aux alentours</h2><button type="button" data-go="people">Tout voir →</button></div><div class="peopleList">${list.slice(0,3).map(p=>personCard(p,true,p._d)).join('')}</div>`}
function ensureModal(){if(document.getElementById('publishModal'))return;document.body.insertAdjacentHTML('beforeend','<div class="publishModal" id="publishModal"><div class="publishSheet"><div class="publishSheetHead"><h2 id="publishTitle">Publier</h2><button class="closeSheet" type="button" data-close-publish>×</button></div><div id="publishBody"></div></div></div>')}
function openPublish(type){ensureModal();const modal=document.getElementById('publishModal'),title=document.getElementById('publishTitle'),body=document.getElementById('publishBody');const names={place:'Publier un lieu',availability:'Publier une disponibilité',event:'Publier un événement',skill:'Publier une compétence'};title.textContent=names[type]||'Publier';let extra='';if(type==='place')extra='<label>Site internet<input name="website" type="url" placeholder="https://..."></label><label>Ville<input name="city" required></label>';if(type==='availability')extra='<label>Lieu<input name="city" placeholder="Où travailles-tu ?" required></label><label>Jusqu’à<input name="until" type="time"></label>';if(type==='event')extra='<label>Date et heure<input name="date" type="datetime-local" required></label><label>Lieu<input name="city" required></label>';if(type==='skill')extra='<label>Domaine<input name="category" placeholder="Ex. graphisme, menuiserie…" required></label>';body.innerHTML=`<form class="publishForm" data-publish-form="${type}"><label>Titre<input name="title" maxlength="90" required placeholder="Titre clair et court"></label>${extra}<label>Description<textarea name="desc" maxlength="600" required placeholder="Décris ce que tu proposes…"></textarea></label><button class="submit" type="submit">Publier maintenant</button></form>`;modal.classList.add('show')}
function submitPublish(form){const fd=new FormData(form),type=form.dataset.publishForm,item={id:'user-'+Date.now(),type,title:fd.get('title'),desc:fd.get('desc'),city:fd.get('city')||'',website:fd.get('website')||'',kind:type==='place'?'cowork':'',open:'Publié par la communauté',rating:'—',distanceKm:null,createdAt:new Date().toISOString(),data:Object.fromEntries(fd.entries())};const list=readPublished();list.unshift(item);savePublished(list);form.outerHTML='<div class="publishSuccess">✓ Publication enregistrée. Elle est maintenant disponible dans Cowork it.</div>';if(type==='place')setTimeout(renderPlaces,50)}
function wire(){document.addEventListener('click',e=>{const pub=e.target.closest('.pub');if(pub){const buttons=[...document.querySelectorAll('.publishCards .pub')],idx=buttons.indexOf(pub),types=['place','availability','event','skill'];openPublish(types[idx]);return}if(e.target.closest('[data-close-publish]')||e.target.id==='publishModal'){document.getElementById('publishModal')?.classList.remove('show');return}const map=e.target.closest('[data-place-map]');if(map){window.open('https://www.openstreetmap.org/search?query='+encodeURIComponent(map.dataset.placeMap),'_blank','noopener');return}const seg=e.target.closest('[data-page="people"] .seg button');if(seg){const idx=[...seg.parentElement.children].indexOf(seg);setPeopleMode(['discover','online','near'][idx]);return}const c=e.target.closest('[data-connect]');if(c){alert('Demande de mise en relation envoyée.');return}});document.addEventListener('submit',e=>{const f=e.target.closest('[data-publish-form]');if(f){e.preventDefault();submitPublish(f)}});document.getElementById('exploreSearch')?.addEventListener('input',renderPlaces)}
function boot(){renderPlaces();renderPeople('discover');wire()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();